### ISSUE TITLE
Suggestion: 4-column mode for full-screen HD

### ISSUE THREAD

**Issue by devio-at** [kmc059000/octordle#19]
Hi,

I found that full HD (1920px) allows for display of 4 columns, resulting in 2 rows that barely need scrolling.

In CSS, the required changes for `/v2/` would be:

`.normal-boards`
remove `max-width: 550px;`

`.normal-boards > *`
change width to `width: calc(25% - 20px);`

**Comment by kmc059000** [comment]
Why not use widescreen mode which you can turn on in settings and is allowed when the window is at least 1512 pixels wide? I don't really want to have to support a 3rd UI layout. And after trying it out, I'm not convinced it looks very good. It would require setting responsive breakpoints to make it look good and prevent it from looking stretched like I am seeing on my monitor. Which is not something I am interested in due to the existing widescreen mode. If I am missing something, please clarify as there may still be a good reason. Thank you!

Suggested View:
<img width="2546" alt="image" src="https://user-images.githubusercontent.com/660670/173211043-c9bbbdcb-e699-40f1-94e9-1ce59323e41f.png">

Existing widescreen View:
![image](https://user-images.githubusercontent.com/660670/173211054-9e70b249-caef-45e9-bf36-4d84bf419f49.png)

**Comment by devio-at** [comment]
I never noticed the widescreen mode, and will post a follow-up issue on that.

Thanks for pointing it out
