### ISSUE TITLE
Scoring suggestion

### ISSUE THREAD

**Issue by jeboo** [kmc059000/octordle#21]
Heya, great idea to add scoring! One idea I thought of to make it simpler to understand is to scale it, say 0-100. That way higher numbers equate to better scores and there's no arbitrary range (36-112). The formula would be:

(1-(score/min)/(max - min))*100

You'd probably want to keep one number after the decimal for scores <= 8  or 13 to avoid being confused with # words right or guesses. This kind of scoring would also be portable to the other multiword variants =)

Keep up the good work!

**Comment by kmc059000** [comment]
Hi, thank you for the suggestion! The original scoring mechanism had some of these components (higher was better), but too many people had preexisting expectations of the way scoring worked and reported bugs despite it being intentionally designed.

I ended up switching to the simple scoring mode that exists today for that reason. I even considered removing scores entirely due to people's preexisting expectations of what a score meant to avoid the questions. See below for what my intention for the scores feature was.

While I do like the idea of removing the arbitrary range and more or less normalizing it to a percentage, it would lead to even more questions that I don't want to get. 

AFAIK the other variants don't have scores, and even if they did, I don't feel the scores are comparable or should be comparable across the variants. If multiple other variants implemented a consistent scoring mechanism, I could then be convinced. 

## Design Goal of Scores
NOTE: I include this here for posterity and to refer others to in the future.

When I included scores initially, my goal was to simply implement something that allowed people to compare their scores to each other so they could easily tell who did better. Better being fewest guesses. I always thought the numbers were absolutely meaningless other than for comparison purposes.

There are numerous ways to do this, but ultimately I decided that the simplest, least surprising method for calculating them simply adding up the # of guesses it took to solve each word and having a penalty for a missed word.

I also needed scoring to work for different modes of octordle. I am introducing a few new features where you can have more than 13 guesses, and I wanted the scoring mechanism to work in these modes.
